// Этот файл сгенерирован scripts/build-edge-shared.mjs.
// Изменяйте исходные константы приложения и запускайте генератор.

export type ChessmateHotelHeaderStatus = 'active' | 'mirror' | 'access' | 'request';

export const DEFAULT_CITIES = [
    { value: "sukhumi", label: "Сухум" },
    { value: "new-athon", label: "Новый Афон" },
    { value: "gudauta", label: "Гудаута" },
    { value: "ldzaa", label: "Лдзаа" },
    { value: "pitsunda", label: "Пицунда" },
    { value: "alahadzy", label: "Алахадзы" },
    { value: "gagra", label: "Гагра" },
    { value: "candripsh", label: "Цандрипш" },
] as const;

const MIRROR_HOTEL_TITLES = new Set<string>([
    "сан амра sun amra",
    "нора",
    "студио сан амра",
    "санрайз гостевой дом",
    "фемели",
    "аврора inn",
    "блэк си",
    "лазурит",
    "грасс",
    "джаннат",
    "вилла оазис",
    "вилла леона",
    "барнаба",
    "рита",
    "александрия",
    "белая лошадь white horse",
    "грей хаус grey house",
    "грин вилладж greenvillage",
    "санни хоум",
    "каво де буксо",
    "эсма",
    "сизон",
    "дыши глубже",
]);

const CHESSMATE_STATUS_BY_HOTEL_TITLE: Record<string, ChessmateHotelHeaderStatus> = {
    "абаза": "request",
    "абырлаш": "request",
    "адунеи гостевой дом": "active",
    "аврора inn": "active",
    "аквамарин дом под ключ": "active",
    "александрия": "access",
    "амзара": "request",
    "амина дом под ключ": "active",
    "амор": "active",
    "апра": "active",
    "апса apsa": "request",
    "арина": "active",
    "ассир": "active",
    "багрипш домики на берегу с питанием": "active",
    "банан и фундук": "active",
    "белая дача": "active",
    "белая лошадь white horse": "access",
    "белый дом": "request",
    "бельведер": "active",
    "бригантина": "active",
    "бриз": "active",
    "бзыбь": "access",
    "би хэппи be happy": "active",
    "бугенвиллея": "active",
    "белочка": "active",
    "в синопе": "active",
    "вилла лаванда": "request",
    "вилла любовь": "active",
    "восходящая звезда": "active",
    "грант grant": "access",
    "грей хаус grey house": "access",
    "грейс квартира 2к": "active",
    "грин вилладж greenvillage": "access",
    "грин хаус green house": "active",
    "дамира": "access",
    "данелян": "access",
    "дельфин": "request",
    "демимокко demi mokko": "active",
    "домики у марины": "active",
    "дыши глубже": "access",
    "зеленый дворик": "active",
    "каво де буксо": "access",
    "камелия": "active",
    "каралина апартаменты": "active",
    "карин": "active",
    "кастл castle": "active",
    "кира guest house kira": "active",
    "киараз резорт": "active",
    "крылья": "active",
    "лазурит": "access",
    "лайм": "request",
    "лемар": "access",
    "лето квартира 2к": "active",
    "лимон": "access",
    "мадлена": "active",
    "мандариновый дворик дом под ключ": "active",
    "маре дольче": "access",
    "мзия": "active",
    "мика": "active",
    "мокко апартаменты": "active",
    "мореон": "active",
    "мореон квартира 2к": "active",
    "морская лагуна": "active",
    "пицунда": "access",
    "мулберри": "active",
    "на время в раю полдома под ключ": "active",
    "николь": "active",
    "никопсия": "request",
    "нора": "access",
    "парус": "active",
    "пегас": "active",
    "песчаный берег апартаменты": "active",
    "пляжный комплекс 151": "active",
    "райский берег": "active",
    "ранчо эли вэл": "active",
    "рита": "access",
    "сан амра sun amra": "access",
    "сан пино sun pino": "access",
    "санди хаус": "request",
    "санни хоум": "access",
    "санрайз гостевой дом": "access",
    "сансет sunset квартира 2к": "active",
    "сансет домики": "access",
    "секрет гарден апартаменты": "active",
    "сизон": "access",
    "симона": "active",
    "сисайд хаус seasidehouse": "access",
    "старый причал": "access",
    "сухум дом под ключ": "active",
    "тис": "access",
    "феникс дом под ключ": "active",
    "фламинго гостевой дом": "active",
    "флора flora дом": "active",
    "эсма": "access",
    "акварель три 2к квартиры": "active",
    "акира квартира 2к": "active",
    "акиртава квартира 3к": "active",
    "аниса квартира 1к": "active",
    "арго квартира 1к": "active",
    "атмосферная квартира 2к": "active",
    "афина квартира 2к": "active",
    "бирюза апартаменты": "active",
    "виктория квартира 2к": "active",
    "заречный этаж в доме под ключ": "active",
    "камилла квартира 2к": "active",
    "кипарисовая квартира 1к": "active",
    "классика квартира 2к": "active",
    "курортная квартира 2к": "active",
    "ладария 1к квартира": "active",
    "летняя квартира 3к": "active",
    "магнолия квартира 3к": "active",
    "мансарда квартира 2к": "active",
    "мелана квартира 3к": "active",
    "мечта аппартаменты": "request",
    "мимоза квартира 3к": "active",
    "мира дом под ключ": "active",
    "мия дом под ключ": "active",
    "мон амур monamour квартира 1к": "active",
    "монро квартира 3к": "active",
    "на высоте квартира 2к": "active",
    "на пляже квартира 3к": "active",
    "нонна квартира 2к": "active",
    "пальма квартира 3к": "active",
    "парковая квартира 2к": "active",
    "питиунт квартира 4к": "active",
    "семейная квартира 2к": "active",
    "сити гагра citygagra квартира 2к": "active",
    "солнечная квартира 2к": "active",
    "сосновая квартира 1к": "active",
    "тихая обитель дом под ключ": "active",
    "центральный дом под ключ": "active",
    "черноморские квартиры 2к": "active",
    "южное утро и тихая бухта апартаменты": "active",
};

const normalizeHotelTitle = (title: string) =>
    title
        .toLowerCase()
        .replaceAll('ё', 'е')
        .replace(/[“”"«»()\-.,]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();

export const getChessmateHotelHeaderStatus = (
    title?: string | null,
): ChessmateHotelHeaderStatus | undefined => {
    if (!title) return undefined;

    const normalizedTitle = normalizeHotelTitle(title);

    if (MIRROR_HOTEL_TITLES.has(normalizedTitle)) return 'mirror';

    return CHESSMATE_STATUS_BY_HOTEL_TITLE[normalizedTitle];
};
