export enum PagesEnum {
    MAIN = 'MAIN',
    HOTELS = 'HOTELS',
    RESERVATION = 'RESERVATION',
    OPERATIONS = 'OPERATIONS',
    LOGIN = 'LOGIN',
    ADVANCED_FILTERS = 'ADVANCED_FILTERS',
    ADMIN_OPERATORS = 'ADMIN_OPERATORS',
    BOOKINGS = 'BOOKINGS',
    MORNING = 'MORNING',
    DEALS = 'DEALS',
    CLIENTS = 'CLIENTS',
    IMPORT = 'IMPORT',
    FINANCE = 'FINANCE',
    MY_FINANCE = 'MY_FINANCE',
    INBOX = 'INBOX',
    INSTAGRAM = 'INSTAGRAM',
    OBJECTS = 'OBJECTS',
    MY_HOTEL = 'MY_HOTEL',
}

export const routes = {
    [PagesEnum.MAIN]: '/main',
    [PagesEnum.HOTELS]: '/main/hotels',
    [PagesEnum.RESERVATION]: '/main/reservation',
    [PagesEnum.OPERATIONS]: '/main/operations',
    [PagesEnum.BOOKINGS]: '/main/bookings',
    [PagesEnum.MORNING]: '/main/morning',
    [PagesEnum.DEALS]: '/main/deals',
    [PagesEnum.CLIENTS]: '/main/clients',
    [PagesEnum.IMPORT]: '/main/import',
    [PagesEnum.FINANCE]: '/main/finance',
    [PagesEnum.MY_FINANCE]: '/main/my-finance',
    [PagesEnum.INBOX]: '/main/inbox',
    [PagesEnum.INSTAGRAM]: '/main/instagram',
    [PagesEnum.OBJECTS]: '/main/objects',
    [PagesEnum.MY_HOTEL]: '/main/my-hotel',
    [PagesEnum.LOGIN]: '/login',
    [PagesEnum.ADVANCED_FILTERS]: '/advanced-filters',
    [PagesEnum.ADMIN_OPERATORS]: '/main/admin/operators',
};
