openapi: 3.0.0
info:
  title: Travel Time
  version: 1.0.0
paths:
  /:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: ${CONTAINER_ID}
        service_account_id: ${SERVICE_ACCOUNT_ID}
  /{proxy+}:
    x-yc-apigateway-any-method:
      parameters:
        - name: proxy
          in: path
          required: false
          schema:
            type: string
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: ${CONTAINER_ID}
        service_account_id: ${SERVICE_ACCOUNT_ID}
